// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class CBlockInfo;
@class CBlockInfoBuilder;
@class CContactInfo;
@class CContactInfoBuilder;
@class CFansInfo;
@class CFansInfoBuilder;
@class CFollowAddBlockReq;
@class CFollowAddBlockReqBuilder;
@class CFollowAddBlockResp;
@class CFollowAddBlockRespBuilder;
@class CFollowAddReq;
@class CFollowAddReqBuilder;
@class CFollowAddResp;
@class CFollowAddRespBuilder;
@class CFollowDeleteBlockReq;
@class CFollowDeleteBlockReqBuilder;
@class CFollowDeleteBlockResp;
@class CFollowDeleteBlockRespBuilder;
@class CFollowDeleteContactReq;
@class CFollowDeleteContactReqBuilder;
@class CFollowDeleteContactResp;
@class CFollowDeleteContactRespBuilder;
@class CFollowDeleteReq;
@class CFollowDeleteReqBuilder;
@class CFollowDeleteResp;
@class CFollowDeleteRespBuilder;
@class CFollowGetBlockListReq;
@class CFollowGetBlockListReqBuilder;
@class CFollowGetBlockListResp;
@class CFollowGetBlockListRespBuilder;
@class CFollowGetContactListReq;
@class CFollowGetContactListReqBuilder;
@class CFollowGetContactListResp;
@class CFollowGetContactListRespBuilder;
@class CFollowGetFansListReq;
@class CFollowGetFansListReqBuilder;
@class CFollowGetFansListResp;
@class CFollowGetFansListRespBuilder;
@class CFollowGetInfoReq;
@class CFollowGetInfoReqBuilder;
@class CFollowGetInfoResp;
@class CFollowGetInfoRespBuilder;
@class CFollowGetListReq;
@class CFollowGetListReqBuilder;
@class CFollowGetListResp;
@class CFollowGetListRespBuilder;
@class CFollowInfo;
@class CFollowInfoBuilder;
@class CFollowSetInfoReq;
@class CFollowSetInfoReqBuilder;
@class CFollowSetInfoResp;
@class CFollowSetInfoRespBuilder;



@interface FollowRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface CFollowGetListReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLimit_:1;
  BOOL hasPage_:1;
  UInt32 limit;
  UInt32 page;
}
- (BOOL) hasLimit;
- (BOOL) hasPage;
@property (readonly) UInt32 limit;
@property (readonly) UInt32 page;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowGetListReqBuilder*) builder;
+ (CFollowGetListReqBuilder*) builder;
+ (CFollowGetListReqBuilder*) builderWithPrototype:(CFollowGetListReq*) prototype;
- (CFollowGetListReqBuilder*) toBuilder;

+ (CFollowGetListReq*) parseFromData:(NSData*) data;
+ (CFollowGetListReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetListReq*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowGetListReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowGetListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowGetListReqBuilder : PBGeneratedMessageBuilder {
@private
  CFollowGetListReq* resultCfollowGetListReq;
}

- (CFollowGetListReq*) defaultInstance;

- (CFollowGetListReqBuilder*) clear;
- (CFollowGetListReqBuilder*) clone;

- (CFollowGetListReq*) build;
- (CFollowGetListReq*) buildPartial;

- (CFollowGetListReqBuilder*) mergeFrom:(CFollowGetListReq*) other;
- (CFollowGetListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowGetListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLimit;
- (UInt32) limit;
- (CFollowGetListReqBuilder*) setLimit:(UInt32) value;
- (CFollowGetListReqBuilder*) clearLimit;

- (BOOL) hasPage;
- (UInt32) page;
- (CFollowGetListReqBuilder*) setPage:(UInt32) value;
- (CFollowGetListReqBuilder*) clearPage;
@end

@interface CFollowInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  BOOL hasMemo_:1;
  BOOL hasHeadimg_:1;
  BOOL hasLastMsgData_:1;
  BOOL hasTid_:1;
  BOOL hasUnread_:1;
  UInt64 uid;
  NSString* memo;
  NSString* headimg;
  NSData* lastMsgData;
  UInt32 tid;
  UInt32 unread;
}
- (BOOL) hasUid;
- (BOOL) hasTid;
- (BOOL) hasMemo;
- (BOOL) hasLastMsgData;
- (BOOL) hasUnread;
- (BOOL) hasHeadimg;
@property (readonly) UInt64 uid;
@property (readonly) UInt32 tid;
@property (readonly, strong) NSString* memo;
@property (readonly, strong) NSData* lastMsgData;
@property (readonly) UInt32 unread;
@property (readonly, strong) NSString* headimg;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowInfoBuilder*) builder;
+ (CFollowInfoBuilder*) builder;
+ (CFollowInfoBuilder*) builderWithPrototype:(CFollowInfo*) prototype;
- (CFollowInfoBuilder*) toBuilder;

+ (CFollowInfo*) parseFromData:(NSData*) data;
+ (CFollowInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowInfo*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowInfoBuilder : PBGeneratedMessageBuilder {
@private
  CFollowInfo* resultCfollowInfo;
}

- (CFollowInfo*) defaultInstance;

- (CFollowInfoBuilder*) clear;
- (CFollowInfoBuilder*) clone;

- (CFollowInfo*) build;
- (CFollowInfo*) buildPartial;

- (CFollowInfoBuilder*) mergeFrom:(CFollowInfo*) other;
- (CFollowInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt64) uid;
- (CFollowInfoBuilder*) setUid:(UInt64) value;
- (CFollowInfoBuilder*) clearUid;

- (BOOL) hasTid;
- (UInt32) tid;
- (CFollowInfoBuilder*) setTid:(UInt32) value;
- (CFollowInfoBuilder*) clearTid;

- (BOOL) hasMemo;
- (NSString*) memo;
- (CFollowInfoBuilder*) setMemo:(NSString*) value;
- (CFollowInfoBuilder*) clearMemo;

- (BOOL) hasLastMsgData;
- (NSData*) lastMsgData;
- (CFollowInfoBuilder*) setLastMsgData:(NSData*) value;
- (CFollowInfoBuilder*) clearLastMsgData;

- (BOOL) hasUnread;
- (UInt32) unread;
- (CFollowInfoBuilder*) setUnread:(UInt32) value;
- (CFollowInfoBuilder*) clearUnread;

- (BOOL) hasHeadimg;
- (NSString*) headimg;
- (CFollowInfoBuilder*) setHeadimg:(NSString*) value;
- (CFollowInfoBuilder*) clearHeadimg;
@end

@interface CFollowGetListResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * followInfosArray;
}
@property (readonly, strong) NSArray * followInfos;
- (CFollowInfo*)followInfosAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowGetListRespBuilder*) builder;
+ (CFollowGetListRespBuilder*) builder;
+ (CFollowGetListRespBuilder*) builderWithPrototype:(CFollowGetListResp*) prototype;
- (CFollowGetListRespBuilder*) toBuilder;

+ (CFollowGetListResp*) parseFromData:(NSData*) data;
+ (CFollowGetListResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetListResp*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowGetListResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetListResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowGetListResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowGetListRespBuilder : PBGeneratedMessageBuilder {
@private
  CFollowGetListResp* resultCfollowGetListResp;
}

- (CFollowGetListResp*) defaultInstance;

- (CFollowGetListRespBuilder*) clear;
- (CFollowGetListRespBuilder*) clone;

- (CFollowGetListResp*) build;
- (CFollowGetListResp*) buildPartial;

- (CFollowGetListRespBuilder*) mergeFrom:(CFollowGetListResp*) other;
- (CFollowGetListRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowGetListRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)followInfos;
- (CFollowInfo*)followInfosAtIndex:(NSUInteger)index;
- (CFollowGetListRespBuilder *)addFollowInfos:(CFollowInfo*)value;
- (CFollowGetListRespBuilder *)setFollowInfosArray:(NSArray *)array;
- (CFollowGetListRespBuilder *)clearFollowInfos;
@end

@interface CFollowSetInfoReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFollowInfo_:1;
  CFollowInfo* followInfo;
}
- (BOOL) hasFollowInfo;
@property (readonly, strong) CFollowInfo* followInfo;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowSetInfoReqBuilder*) builder;
+ (CFollowSetInfoReqBuilder*) builder;
+ (CFollowSetInfoReqBuilder*) builderWithPrototype:(CFollowSetInfoReq*) prototype;
- (CFollowSetInfoReqBuilder*) toBuilder;

+ (CFollowSetInfoReq*) parseFromData:(NSData*) data;
+ (CFollowSetInfoReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowSetInfoReq*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowSetInfoReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowSetInfoReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowSetInfoReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowSetInfoReqBuilder : PBGeneratedMessageBuilder {
@private
  CFollowSetInfoReq* resultCfollowSetInfoReq;
}

- (CFollowSetInfoReq*) defaultInstance;

- (CFollowSetInfoReqBuilder*) clear;
- (CFollowSetInfoReqBuilder*) clone;

- (CFollowSetInfoReq*) build;
- (CFollowSetInfoReq*) buildPartial;

- (CFollowSetInfoReqBuilder*) mergeFrom:(CFollowSetInfoReq*) other;
- (CFollowSetInfoReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowSetInfoReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFollowInfo;
- (CFollowInfo*) followInfo;
- (CFollowSetInfoReqBuilder*) setFollowInfo:(CFollowInfo*) value;
- (CFollowSetInfoReqBuilder*) setFollowInfoBuilder:(CFollowInfoBuilder*) builderForValue;
- (CFollowSetInfoReqBuilder*) mergeFollowInfo:(CFollowInfo*) value;
- (CFollowSetInfoReqBuilder*) clearFollowInfo;
@end

@interface CFollowSetInfoResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFollowInfo_:1;
  CFollowInfo* followInfo;
}
- (BOOL) hasFollowInfo;
@property (readonly, strong) CFollowInfo* followInfo;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowSetInfoRespBuilder*) builder;
+ (CFollowSetInfoRespBuilder*) builder;
+ (CFollowSetInfoRespBuilder*) builderWithPrototype:(CFollowSetInfoResp*) prototype;
- (CFollowSetInfoRespBuilder*) toBuilder;

+ (CFollowSetInfoResp*) parseFromData:(NSData*) data;
+ (CFollowSetInfoResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowSetInfoResp*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowSetInfoResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowSetInfoResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowSetInfoResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowSetInfoRespBuilder : PBGeneratedMessageBuilder {
@private
  CFollowSetInfoResp* resultCfollowSetInfoResp;
}

- (CFollowSetInfoResp*) defaultInstance;

- (CFollowSetInfoRespBuilder*) clear;
- (CFollowSetInfoRespBuilder*) clone;

- (CFollowSetInfoResp*) build;
- (CFollowSetInfoResp*) buildPartial;

- (CFollowSetInfoRespBuilder*) mergeFrom:(CFollowSetInfoResp*) other;
- (CFollowSetInfoRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowSetInfoRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFollowInfo;
- (CFollowInfo*) followInfo;
- (CFollowSetInfoRespBuilder*) setFollowInfo:(CFollowInfo*) value;
- (CFollowSetInfoRespBuilder*) setFollowInfoBuilder:(CFollowInfoBuilder*) builderForValue;
- (CFollowSetInfoRespBuilder*) mergeFollowInfo:(CFollowInfo*) value;
- (CFollowSetInfoRespBuilder*) clearFollowInfo;
@end

@interface CFollowGetInfoReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  UInt64 uid;
}
- (BOOL) hasUid;
@property (readonly) UInt64 uid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowGetInfoReqBuilder*) builder;
+ (CFollowGetInfoReqBuilder*) builder;
+ (CFollowGetInfoReqBuilder*) builderWithPrototype:(CFollowGetInfoReq*) prototype;
- (CFollowGetInfoReqBuilder*) toBuilder;

+ (CFollowGetInfoReq*) parseFromData:(NSData*) data;
+ (CFollowGetInfoReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetInfoReq*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowGetInfoReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetInfoReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowGetInfoReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowGetInfoReqBuilder : PBGeneratedMessageBuilder {
@private
  CFollowGetInfoReq* resultCfollowGetInfoReq;
}

- (CFollowGetInfoReq*) defaultInstance;

- (CFollowGetInfoReqBuilder*) clear;
- (CFollowGetInfoReqBuilder*) clone;

- (CFollowGetInfoReq*) build;
- (CFollowGetInfoReq*) buildPartial;

- (CFollowGetInfoReqBuilder*) mergeFrom:(CFollowGetInfoReq*) other;
- (CFollowGetInfoReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowGetInfoReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt64) uid;
- (CFollowGetInfoReqBuilder*) setUid:(UInt64) value;
- (CFollowGetInfoReqBuilder*) clearUid;
@end

@interface CFollowGetInfoResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFollowInfo_:1;
  CFollowInfo* followInfo;
}
- (BOOL) hasFollowInfo;
@property (readonly, strong) CFollowInfo* followInfo;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowGetInfoRespBuilder*) builder;
+ (CFollowGetInfoRespBuilder*) builder;
+ (CFollowGetInfoRespBuilder*) builderWithPrototype:(CFollowGetInfoResp*) prototype;
- (CFollowGetInfoRespBuilder*) toBuilder;

+ (CFollowGetInfoResp*) parseFromData:(NSData*) data;
+ (CFollowGetInfoResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetInfoResp*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowGetInfoResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetInfoResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowGetInfoResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowGetInfoRespBuilder : PBGeneratedMessageBuilder {
@private
  CFollowGetInfoResp* resultCfollowGetInfoResp;
}

- (CFollowGetInfoResp*) defaultInstance;

- (CFollowGetInfoRespBuilder*) clear;
- (CFollowGetInfoRespBuilder*) clone;

- (CFollowGetInfoResp*) build;
- (CFollowGetInfoResp*) buildPartial;

- (CFollowGetInfoRespBuilder*) mergeFrom:(CFollowGetInfoResp*) other;
- (CFollowGetInfoRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowGetInfoRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFollowInfo;
- (CFollowInfo*) followInfo;
- (CFollowGetInfoRespBuilder*) setFollowInfo:(CFollowInfo*) value;
- (CFollowGetInfoRespBuilder*) setFollowInfoBuilder:(CFollowInfoBuilder*) builderForValue;
- (CFollowGetInfoRespBuilder*) mergeFollowInfo:(CFollowInfo*) value;
- (CFollowGetInfoRespBuilder*) clearFollowInfo;
@end

@interface CFollowAddReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAddUid_:1;
  UInt64 addUid;
}
- (BOOL) hasAddUid;
@property (readonly) UInt64 addUid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowAddReqBuilder*) builder;
+ (CFollowAddReqBuilder*) builder;
+ (CFollowAddReqBuilder*) builderWithPrototype:(CFollowAddReq*) prototype;
- (CFollowAddReqBuilder*) toBuilder;

+ (CFollowAddReq*) parseFromData:(NSData*) data;
+ (CFollowAddReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowAddReq*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowAddReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowAddReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowAddReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowAddReqBuilder : PBGeneratedMessageBuilder {
@private
  CFollowAddReq* resultCfollowAddReq;
}

- (CFollowAddReq*) defaultInstance;

- (CFollowAddReqBuilder*) clear;
- (CFollowAddReqBuilder*) clone;

- (CFollowAddReq*) build;
- (CFollowAddReq*) buildPartial;

- (CFollowAddReqBuilder*) mergeFrom:(CFollowAddReq*) other;
- (CFollowAddReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowAddReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAddUid;
- (UInt64) addUid;
- (CFollowAddReqBuilder*) setAddUid:(UInt64) value;
- (CFollowAddReqBuilder*) clearAddUid;
@end

@interface CFollowAddResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowAddRespBuilder*) builder;
+ (CFollowAddRespBuilder*) builder;
+ (CFollowAddRespBuilder*) builderWithPrototype:(CFollowAddResp*) prototype;
- (CFollowAddRespBuilder*) toBuilder;

+ (CFollowAddResp*) parseFromData:(NSData*) data;
+ (CFollowAddResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowAddResp*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowAddResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowAddResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowAddResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowAddRespBuilder : PBGeneratedMessageBuilder {
@private
  CFollowAddResp* resultCfollowAddResp;
}

- (CFollowAddResp*) defaultInstance;

- (CFollowAddRespBuilder*) clear;
- (CFollowAddRespBuilder*) clone;

- (CFollowAddResp*) build;
- (CFollowAddResp*) buildPartial;

- (CFollowAddRespBuilder*) mergeFrom:(CFollowAddResp*) other;
- (CFollowAddRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowAddRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowDeleteReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDelUid_:1;
  UInt64 delUid;
}
- (BOOL) hasDelUid;
@property (readonly) UInt64 delUid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowDeleteReqBuilder*) builder;
+ (CFollowDeleteReqBuilder*) builder;
+ (CFollowDeleteReqBuilder*) builderWithPrototype:(CFollowDeleteReq*) prototype;
- (CFollowDeleteReqBuilder*) toBuilder;

+ (CFollowDeleteReq*) parseFromData:(NSData*) data;
+ (CFollowDeleteReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowDeleteReq*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowDeleteReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowDeleteReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowDeleteReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowDeleteReqBuilder : PBGeneratedMessageBuilder {
@private
  CFollowDeleteReq* resultCfollowDeleteReq;
}

- (CFollowDeleteReq*) defaultInstance;

- (CFollowDeleteReqBuilder*) clear;
- (CFollowDeleteReqBuilder*) clone;

- (CFollowDeleteReq*) build;
- (CFollowDeleteReq*) buildPartial;

- (CFollowDeleteReqBuilder*) mergeFrom:(CFollowDeleteReq*) other;
- (CFollowDeleteReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowDeleteReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDelUid;
- (UInt64) delUid;
- (CFollowDeleteReqBuilder*) setDelUid:(UInt64) value;
- (CFollowDeleteReqBuilder*) clearDelUid;
@end

@interface CFollowDeleteResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowDeleteRespBuilder*) builder;
+ (CFollowDeleteRespBuilder*) builder;
+ (CFollowDeleteRespBuilder*) builderWithPrototype:(CFollowDeleteResp*) prototype;
- (CFollowDeleteRespBuilder*) toBuilder;

+ (CFollowDeleteResp*) parseFromData:(NSData*) data;
+ (CFollowDeleteResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowDeleteResp*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowDeleteResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowDeleteResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowDeleteResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowDeleteRespBuilder : PBGeneratedMessageBuilder {
@private
  CFollowDeleteResp* resultCfollowDeleteResp;
}

- (CFollowDeleteResp*) defaultInstance;

- (CFollowDeleteRespBuilder*) clear;
- (CFollowDeleteRespBuilder*) clone;

- (CFollowDeleteResp*) build;
- (CFollowDeleteResp*) buildPartial;

- (CFollowDeleteRespBuilder*) mergeFrom:(CFollowDeleteResp*) other;
- (CFollowDeleteRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowDeleteRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowAddBlockReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBlockUid_:1;
  UInt64 blockUid;
}
- (BOOL) hasBlockUid;
@property (readonly) UInt64 blockUid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowAddBlockReqBuilder*) builder;
+ (CFollowAddBlockReqBuilder*) builder;
+ (CFollowAddBlockReqBuilder*) builderWithPrototype:(CFollowAddBlockReq*) prototype;
- (CFollowAddBlockReqBuilder*) toBuilder;

+ (CFollowAddBlockReq*) parseFromData:(NSData*) data;
+ (CFollowAddBlockReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowAddBlockReq*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowAddBlockReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowAddBlockReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowAddBlockReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowAddBlockReqBuilder : PBGeneratedMessageBuilder {
@private
  CFollowAddBlockReq* resultCfollowAddBlockReq;
}

- (CFollowAddBlockReq*) defaultInstance;

- (CFollowAddBlockReqBuilder*) clear;
- (CFollowAddBlockReqBuilder*) clone;

- (CFollowAddBlockReq*) build;
- (CFollowAddBlockReq*) buildPartial;

- (CFollowAddBlockReqBuilder*) mergeFrom:(CFollowAddBlockReq*) other;
- (CFollowAddBlockReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowAddBlockReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBlockUid;
- (UInt64) blockUid;
- (CFollowAddBlockReqBuilder*) setBlockUid:(UInt64) value;
- (CFollowAddBlockReqBuilder*) clearBlockUid;
@end

@interface CFollowAddBlockResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowAddBlockRespBuilder*) builder;
+ (CFollowAddBlockRespBuilder*) builder;
+ (CFollowAddBlockRespBuilder*) builderWithPrototype:(CFollowAddBlockResp*) prototype;
- (CFollowAddBlockRespBuilder*) toBuilder;

+ (CFollowAddBlockResp*) parseFromData:(NSData*) data;
+ (CFollowAddBlockResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowAddBlockResp*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowAddBlockResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowAddBlockResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowAddBlockResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowAddBlockRespBuilder : PBGeneratedMessageBuilder {
@private
  CFollowAddBlockResp* resultCfollowAddBlockResp;
}

- (CFollowAddBlockResp*) defaultInstance;

- (CFollowAddBlockRespBuilder*) clear;
- (CFollowAddBlockRespBuilder*) clone;

- (CFollowAddBlockResp*) build;
- (CFollowAddBlockResp*) buildPartial;

- (CFollowAddBlockRespBuilder*) mergeFrom:(CFollowAddBlockResp*) other;
- (CFollowAddBlockRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowAddBlockRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowDeleteBlockReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBlockUid_:1;
  UInt64 blockUid;
}
- (BOOL) hasBlockUid;
@property (readonly) UInt64 blockUid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowDeleteBlockReqBuilder*) builder;
+ (CFollowDeleteBlockReqBuilder*) builder;
+ (CFollowDeleteBlockReqBuilder*) builderWithPrototype:(CFollowDeleteBlockReq*) prototype;
- (CFollowDeleteBlockReqBuilder*) toBuilder;

+ (CFollowDeleteBlockReq*) parseFromData:(NSData*) data;
+ (CFollowDeleteBlockReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowDeleteBlockReq*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowDeleteBlockReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowDeleteBlockReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowDeleteBlockReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowDeleteBlockReqBuilder : PBGeneratedMessageBuilder {
@private
  CFollowDeleteBlockReq* resultCfollowDeleteBlockReq;
}

- (CFollowDeleteBlockReq*) defaultInstance;

- (CFollowDeleteBlockReqBuilder*) clear;
- (CFollowDeleteBlockReqBuilder*) clone;

- (CFollowDeleteBlockReq*) build;
- (CFollowDeleteBlockReq*) buildPartial;

- (CFollowDeleteBlockReqBuilder*) mergeFrom:(CFollowDeleteBlockReq*) other;
- (CFollowDeleteBlockReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowDeleteBlockReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBlockUid;
- (UInt64) blockUid;
- (CFollowDeleteBlockReqBuilder*) setBlockUid:(UInt64) value;
- (CFollowDeleteBlockReqBuilder*) clearBlockUid;
@end

@interface CFollowDeleteBlockResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowDeleteBlockRespBuilder*) builder;
+ (CFollowDeleteBlockRespBuilder*) builder;
+ (CFollowDeleteBlockRespBuilder*) builderWithPrototype:(CFollowDeleteBlockResp*) prototype;
- (CFollowDeleteBlockRespBuilder*) toBuilder;

+ (CFollowDeleteBlockResp*) parseFromData:(NSData*) data;
+ (CFollowDeleteBlockResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowDeleteBlockResp*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowDeleteBlockResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowDeleteBlockResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowDeleteBlockResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowDeleteBlockRespBuilder : PBGeneratedMessageBuilder {
@private
  CFollowDeleteBlockResp* resultCfollowDeleteBlockResp;
}

- (CFollowDeleteBlockResp*) defaultInstance;

- (CFollowDeleteBlockRespBuilder*) clear;
- (CFollowDeleteBlockRespBuilder*) clone;

- (CFollowDeleteBlockResp*) build;
- (CFollowDeleteBlockResp*) buildPartial;

- (CFollowDeleteBlockRespBuilder*) mergeFrom:(CFollowDeleteBlockResp*) other;
- (CFollowDeleteBlockRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowDeleteBlockRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowGetBlockListReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowGetBlockListReqBuilder*) builder;
+ (CFollowGetBlockListReqBuilder*) builder;
+ (CFollowGetBlockListReqBuilder*) builderWithPrototype:(CFollowGetBlockListReq*) prototype;
- (CFollowGetBlockListReqBuilder*) toBuilder;

+ (CFollowGetBlockListReq*) parseFromData:(NSData*) data;
+ (CFollowGetBlockListReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetBlockListReq*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowGetBlockListReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetBlockListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowGetBlockListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowGetBlockListReqBuilder : PBGeneratedMessageBuilder {
@private
  CFollowGetBlockListReq* resultCfollowGetBlockListReq;
}

- (CFollowGetBlockListReq*) defaultInstance;

- (CFollowGetBlockListReqBuilder*) clear;
- (CFollowGetBlockListReqBuilder*) clone;

- (CFollowGetBlockListReq*) build;
- (CFollowGetBlockListReq*) buildPartial;

- (CFollowGetBlockListReqBuilder*) mergeFrom:(CFollowGetBlockListReq*) other;
- (CFollowGetBlockListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowGetBlockListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowGetBlockListResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * blockInfosArray;
}
@property (readonly, strong) NSArray * blockInfos;
- (CBlockInfo*)blockInfosAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowGetBlockListRespBuilder*) builder;
+ (CFollowGetBlockListRespBuilder*) builder;
+ (CFollowGetBlockListRespBuilder*) builderWithPrototype:(CFollowGetBlockListResp*) prototype;
- (CFollowGetBlockListRespBuilder*) toBuilder;

+ (CFollowGetBlockListResp*) parseFromData:(NSData*) data;
+ (CFollowGetBlockListResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetBlockListResp*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowGetBlockListResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetBlockListResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowGetBlockListResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowGetBlockListRespBuilder : PBGeneratedMessageBuilder {
@private
  CFollowGetBlockListResp* resultCfollowGetBlockListResp;
}

- (CFollowGetBlockListResp*) defaultInstance;

- (CFollowGetBlockListRespBuilder*) clear;
- (CFollowGetBlockListRespBuilder*) clone;

- (CFollowGetBlockListResp*) build;
- (CFollowGetBlockListResp*) buildPartial;

- (CFollowGetBlockListRespBuilder*) mergeFrom:(CFollowGetBlockListResp*) other;
- (CFollowGetBlockListRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowGetBlockListRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)blockInfos;
- (CBlockInfo*)blockInfosAtIndex:(NSUInteger)index;
- (CFollowGetBlockListRespBuilder *)addBlockInfos:(CBlockInfo*)value;
- (CFollowGetBlockListRespBuilder *)setBlockInfosArray:(NSArray *)array;
- (CFollowGetBlockListRespBuilder *)clearBlockInfos;
@end

@interface CBlockInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBlockUid_:1;
  BOOL hasBlockName_:1;
  UInt64 blockUid;
  NSString* blockName;
}
- (BOOL) hasBlockUid;
- (BOOL) hasBlockName;
@property (readonly) UInt64 blockUid;
@property (readonly, strong) NSString* blockName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CBlockInfoBuilder*) builder;
+ (CBlockInfoBuilder*) builder;
+ (CBlockInfoBuilder*) builderWithPrototype:(CBlockInfo*) prototype;
- (CBlockInfoBuilder*) toBuilder;

+ (CBlockInfo*) parseFromData:(NSData*) data;
+ (CBlockInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CBlockInfo*) parseFromInputStream:(NSInputStream*) input;
+ (CBlockInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CBlockInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CBlockInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CBlockInfoBuilder : PBGeneratedMessageBuilder {
@private
  CBlockInfo* resultCblockInfo;
}

- (CBlockInfo*) defaultInstance;

- (CBlockInfoBuilder*) clear;
- (CBlockInfoBuilder*) clone;

- (CBlockInfo*) build;
- (CBlockInfo*) buildPartial;

- (CBlockInfoBuilder*) mergeFrom:(CBlockInfo*) other;
- (CBlockInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CBlockInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBlockUid;
- (UInt64) blockUid;
- (CBlockInfoBuilder*) setBlockUid:(UInt64) value;
- (CBlockInfoBuilder*) clearBlockUid;

- (BOOL) hasBlockName;
- (NSString*) blockName;
- (CBlockInfoBuilder*) setBlockName:(NSString*) value;
- (CBlockInfoBuilder*) clearBlockName;
@end

@interface CFollowGetFansListReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLimit_:1;
  BOOL hasPage_:1;
  UInt32 limit;
  UInt32 page;
}
- (BOOL) hasLimit;
- (BOOL) hasPage;
@property (readonly) UInt32 limit;
@property (readonly) UInt32 page;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowGetFansListReqBuilder*) builder;
+ (CFollowGetFansListReqBuilder*) builder;
+ (CFollowGetFansListReqBuilder*) builderWithPrototype:(CFollowGetFansListReq*) prototype;
- (CFollowGetFansListReqBuilder*) toBuilder;

+ (CFollowGetFansListReq*) parseFromData:(NSData*) data;
+ (CFollowGetFansListReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetFansListReq*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowGetFansListReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetFansListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowGetFansListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowGetFansListReqBuilder : PBGeneratedMessageBuilder {
@private
  CFollowGetFansListReq* resultCfollowGetFansListReq;
}

- (CFollowGetFansListReq*) defaultInstance;

- (CFollowGetFansListReqBuilder*) clear;
- (CFollowGetFansListReqBuilder*) clone;

- (CFollowGetFansListReq*) build;
- (CFollowGetFansListReq*) buildPartial;

- (CFollowGetFansListReqBuilder*) mergeFrom:(CFollowGetFansListReq*) other;
- (CFollowGetFansListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowGetFansListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLimit;
- (UInt32) limit;
- (CFollowGetFansListReqBuilder*) setLimit:(UInt32) value;
- (CFollowGetFansListReqBuilder*) clearLimit;

- (BOOL) hasPage;
- (UInt32) page;
- (CFollowGetFansListReqBuilder*) setPage:(UInt32) value;
- (CFollowGetFansListReqBuilder*) clearPage;
@end

@interface CFansInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  BOOL hasLastMsgid_:1;
  UInt64 uid;
  UInt64 lastMsgid;
}
- (BOOL) hasUid;
- (BOOL) hasLastMsgid;
@property (readonly) UInt64 uid;
@property (readonly) UInt64 lastMsgid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFansInfoBuilder*) builder;
+ (CFansInfoBuilder*) builder;
+ (CFansInfoBuilder*) builderWithPrototype:(CFansInfo*) prototype;
- (CFansInfoBuilder*) toBuilder;

+ (CFansInfo*) parseFromData:(NSData*) data;
+ (CFansInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFansInfo*) parseFromInputStream:(NSInputStream*) input;
+ (CFansInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFansInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFansInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFansInfoBuilder : PBGeneratedMessageBuilder {
@private
  CFansInfo* resultCfansInfo;
}

- (CFansInfo*) defaultInstance;

- (CFansInfoBuilder*) clear;
- (CFansInfoBuilder*) clone;

- (CFansInfo*) build;
- (CFansInfo*) buildPartial;

- (CFansInfoBuilder*) mergeFrom:(CFansInfo*) other;
- (CFansInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFansInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt64) uid;
- (CFansInfoBuilder*) setUid:(UInt64) value;
- (CFansInfoBuilder*) clearUid;

- (BOOL) hasLastMsgid;
- (UInt64) lastMsgid;
- (CFansInfoBuilder*) setLastMsgid:(UInt64) value;
- (CFansInfoBuilder*) clearLastMsgid;
@end

@interface CFollowGetFansListResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * fansInfosArray;
}
@property (readonly, strong) NSArray * fansInfos;
- (CFansInfo*)fansInfosAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowGetFansListRespBuilder*) builder;
+ (CFollowGetFansListRespBuilder*) builder;
+ (CFollowGetFansListRespBuilder*) builderWithPrototype:(CFollowGetFansListResp*) prototype;
- (CFollowGetFansListRespBuilder*) toBuilder;

+ (CFollowGetFansListResp*) parseFromData:(NSData*) data;
+ (CFollowGetFansListResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetFansListResp*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowGetFansListResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetFansListResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowGetFansListResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowGetFansListRespBuilder : PBGeneratedMessageBuilder {
@private
  CFollowGetFansListResp* resultCfollowGetFansListResp;
}

- (CFollowGetFansListResp*) defaultInstance;

- (CFollowGetFansListRespBuilder*) clear;
- (CFollowGetFansListRespBuilder*) clone;

- (CFollowGetFansListResp*) build;
- (CFollowGetFansListResp*) buildPartial;

- (CFollowGetFansListRespBuilder*) mergeFrom:(CFollowGetFansListResp*) other;
- (CFollowGetFansListRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowGetFansListRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)fansInfos;
- (CFansInfo*)fansInfosAtIndex:(NSUInteger)index;
- (CFollowGetFansListRespBuilder *)addFansInfos:(CFansInfo*)value;
- (CFollowGetFansListRespBuilder *)setFansInfosArray:(NSArray *)array;
- (CFollowGetFansListRespBuilder *)clearFansInfos;
@end

@interface CFollowGetContactListReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLimit_:1;
  BOOL hasPage_:1;
  UInt32 limit;
  UInt32 page;
}
- (BOOL) hasLimit;
- (BOOL) hasPage;
@property (readonly) UInt32 limit;
@property (readonly) UInt32 page;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowGetContactListReqBuilder*) builder;
+ (CFollowGetContactListReqBuilder*) builder;
+ (CFollowGetContactListReqBuilder*) builderWithPrototype:(CFollowGetContactListReq*) prototype;
- (CFollowGetContactListReqBuilder*) toBuilder;

+ (CFollowGetContactListReq*) parseFromData:(NSData*) data;
+ (CFollowGetContactListReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetContactListReq*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowGetContactListReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetContactListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowGetContactListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowGetContactListReqBuilder : PBGeneratedMessageBuilder {
@private
  CFollowGetContactListReq* resultCfollowGetContactListReq;
}

- (CFollowGetContactListReq*) defaultInstance;

- (CFollowGetContactListReqBuilder*) clear;
- (CFollowGetContactListReqBuilder*) clone;

- (CFollowGetContactListReq*) build;
- (CFollowGetContactListReq*) buildPartial;

- (CFollowGetContactListReqBuilder*) mergeFrom:(CFollowGetContactListReq*) other;
- (CFollowGetContactListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowGetContactListReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLimit;
- (UInt32) limit;
- (CFollowGetContactListReqBuilder*) setLimit:(UInt32) value;
- (CFollowGetContactListReqBuilder*) clearLimit;

- (BOOL) hasPage;
- (UInt32) page;
- (CFollowGetContactListReqBuilder*) setPage:(UInt32) value;
- (CFollowGetContactListReqBuilder*) clearPage;
@end

@interface CContactInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  BOOL hasSid_:1;
  BOOL hasName_:1;
  BOOL hasHeadimg_:1;
  BOOL hasLastMsgData_:1;
  BOOL hasUnread_:1;
  UInt64 uid;
  NSString* sid;
  NSString* name;
  NSString* headimg;
  NSData* lastMsgData;
  UInt32 unread;
}
- (BOOL) hasUid;
- (BOOL) hasSid;
- (BOOL) hasName;
- (BOOL) hasLastMsgData;
- (BOOL) hasUnread;
- (BOOL) hasHeadimg;
@property (readonly) UInt64 uid;
@property (readonly, strong) NSString* sid;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSData* lastMsgData;
@property (readonly) UInt32 unread;
@property (readonly, strong) NSString* headimg;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CContactInfoBuilder*) builder;
+ (CContactInfoBuilder*) builder;
+ (CContactInfoBuilder*) builderWithPrototype:(CContactInfo*) prototype;
- (CContactInfoBuilder*) toBuilder;

+ (CContactInfo*) parseFromData:(NSData*) data;
+ (CContactInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CContactInfo*) parseFromInputStream:(NSInputStream*) input;
+ (CContactInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CContactInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CContactInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CContactInfoBuilder : PBGeneratedMessageBuilder {
@private
  CContactInfo* resultCcontactInfo;
}

- (CContactInfo*) defaultInstance;

- (CContactInfoBuilder*) clear;
- (CContactInfoBuilder*) clone;

- (CContactInfo*) build;
- (CContactInfo*) buildPartial;

- (CContactInfoBuilder*) mergeFrom:(CContactInfo*) other;
- (CContactInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CContactInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt64) uid;
- (CContactInfoBuilder*) setUid:(UInt64) value;
- (CContactInfoBuilder*) clearUid;

- (BOOL) hasSid;
- (NSString*) sid;
- (CContactInfoBuilder*) setSid:(NSString*) value;
- (CContactInfoBuilder*) clearSid;

- (BOOL) hasName;
- (NSString*) name;
- (CContactInfoBuilder*) setName:(NSString*) value;
- (CContactInfoBuilder*) clearName;

- (BOOL) hasLastMsgData;
- (NSData*) lastMsgData;
- (CContactInfoBuilder*) setLastMsgData:(NSData*) value;
- (CContactInfoBuilder*) clearLastMsgData;

- (BOOL) hasUnread;
- (UInt32) unread;
- (CContactInfoBuilder*) setUnread:(UInt32) value;
- (CContactInfoBuilder*) clearUnread;

- (BOOL) hasHeadimg;
- (NSString*) headimg;
- (CContactInfoBuilder*) setHeadimg:(NSString*) value;
- (CContactInfoBuilder*) clearHeadimg;
@end

@interface CFollowGetContactListResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * contactsArray;
}
@property (readonly, strong) NSArray * contacts;
- (CContactInfo*)contactsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowGetContactListRespBuilder*) builder;
+ (CFollowGetContactListRespBuilder*) builder;
+ (CFollowGetContactListRespBuilder*) builderWithPrototype:(CFollowGetContactListResp*) prototype;
- (CFollowGetContactListRespBuilder*) toBuilder;

+ (CFollowGetContactListResp*) parseFromData:(NSData*) data;
+ (CFollowGetContactListResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetContactListResp*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowGetContactListResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowGetContactListResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowGetContactListResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowGetContactListRespBuilder : PBGeneratedMessageBuilder {
@private
  CFollowGetContactListResp* resultCfollowGetContactListResp;
}

- (CFollowGetContactListResp*) defaultInstance;

- (CFollowGetContactListRespBuilder*) clear;
- (CFollowGetContactListRespBuilder*) clone;

- (CFollowGetContactListResp*) build;
- (CFollowGetContactListResp*) buildPartial;

- (CFollowGetContactListRespBuilder*) mergeFrom:(CFollowGetContactListResp*) other;
- (CFollowGetContactListRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowGetContactListRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)contacts;
- (CContactInfo*)contactsAtIndex:(NSUInteger)index;
- (CFollowGetContactListRespBuilder *)addContacts:(CContactInfo*)value;
- (CFollowGetContactListRespBuilder *)setContactsArray:(NSArray *)array;
- (CFollowGetContactListRespBuilder *)clearContacts;
@end

@interface CFollowDeleteContactReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  UInt64 uid;
}
- (BOOL) hasUid;
@property (readonly) UInt64 uid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowDeleteContactReqBuilder*) builder;
+ (CFollowDeleteContactReqBuilder*) builder;
+ (CFollowDeleteContactReqBuilder*) builderWithPrototype:(CFollowDeleteContactReq*) prototype;
- (CFollowDeleteContactReqBuilder*) toBuilder;

+ (CFollowDeleteContactReq*) parseFromData:(NSData*) data;
+ (CFollowDeleteContactReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowDeleteContactReq*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowDeleteContactReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowDeleteContactReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowDeleteContactReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowDeleteContactReqBuilder : PBGeneratedMessageBuilder {
@private
  CFollowDeleteContactReq* resultCfollowDeleteContactReq;
}

- (CFollowDeleteContactReq*) defaultInstance;

- (CFollowDeleteContactReqBuilder*) clear;
- (CFollowDeleteContactReqBuilder*) clone;

- (CFollowDeleteContactReq*) build;
- (CFollowDeleteContactReq*) buildPartial;

- (CFollowDeleteContactReqBuilder*) mergeFrom:(CFollowDeleteContactReq*) other;
- (CFollowDeleteContactReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowDeleteContactReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt64) uid;
- (CFollowDeleteContactReqBuilder*) setUid:(UInt64) value;
- (CFollowDeleteContactReqBuilder*) clearUid;
@end

@interface CFollowDeleteContactResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFollowDeleteContactRespBuilder*) builder;
+ (CFollowDeleteContactRespBuilder*) builder;
+ (CFollowDeleteContactRespBuilder*) builderWithPrototype:(CFollowDeleteContactResp*) prototype;
- (CFollowDeleteContactRespBuilder*) toBuilder;

+ (CFollowDeleteContactResp*) parseFromData:(NSData*) data;
+ (CFollowDeleteContactResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowDeleteContactResp*) parseFromInputStream:(NSInputStream*) input;
+ (CFollowDeleteContactResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFollowDeleteContactResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFollowDeleteContactResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFollowDeleteContactRespBuilder : PBGeneratedMessageBuilder {
@private
  CFollowDeleteContactResp* resultCfollowDeleteContactResp;
}

- (CFollowDeleteContactResp*) defaultInstance;

- (CFollowDeleteContactRespBuilder*) clear;
- (CFollowDeleteContactRespBuilder*) clone;

- (CFollowDeleteContactResp*) build;
- (CFollowDeleteContactResp*) buildPartial;

- (CFollowDeleteContactRespBuilder*) mergeFrom:(CFollowDeleteContactResp*) other;
- (CFollowDeleteContactRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFollowDeleteContactRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end


// @@protoc_insertion_point(global_scope)
