// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class CMsgAckContent;
@class CMsgAckContentBuilder;
@class CMsgClearOfflineByUidReq;
@class CMsgClearOfflineByUidReqBuilder;
@class CMsgClearOfflineByUidResp;
@class CMsgClearOfflineByUidRespBuilder;
@class CMsgClearUnreadByUidReq;
@class CMsgClearUnreadByUidReqBuilder;
@class CMsgClearUnreadByUidResp;
@class CMsgClearUnreadByUidRespBuilder;
@class CMsgCommonReq;
@class CMsgCommonReqBuilder;
@class CMsgCommonResp;
@class CMsgCommonRespBuilder;
@class CMsgGetHistoryMsgReq;
@class CMsgGetHistoryMsgReqBuilder;
@class CMsgGetHistoryMsgResp;
@class CMsgGetHistoryMsgRespBuilder;
@class CMsgGetLatestMsgReq;
@class CMsgGetLatestMsgReqBuilder;
@class CMsgGetLatestMsgResp;
@class CMsgGetLatestMsgRespBuilder;
@class CMsgGetOfflineCountByUidReq;
@class CMsgGetOfflineCountByUidReqBuilder;
@class CMsgGetOfflineCountByUidResp;
@class CMsgGetOfflineCountByUidRespBuilder;
@class CMsgGetOfflineCountReq;
@class CMsgGetOfflineCountReqBuilder;
@class CMsgGetOfflineCountResp;
@class CMsgGetOfflineCountRespBuilder;
@class CMsgGetOfflineMsgAckReq;
@class CMsgGetOfflineMsgAckReqBuilder;
@class CMsgGetOfflineMsgAckResp;
@class CMsgGetOfflineMsgAckRespBuilder;
@class CMsgGetOfflineMsgReq;
@class CMsgGetOfflineMsgReqBuilder;
@class CMsgGetOfflineMsgResp;
@class CMsgGetOfflineMsgRespBuilder;
@class CMsgMergeMsgReq;
@class CMsgMergeMsgReqBuilder;
@class CMsgMergeMsgResp;
@class CMsgMergeMsgRespBuilder;
@class CMsgOfflineCountInfo;
@class CMsgOfflineCountInfoBuilder;
@class CMsgPBContent;
@class CMsgPBContentBuilder;
@class CMsgPushNotify;
@class CMsgPushNotifyBuilder;
@class CMsgSendAckResp;
@class CMsgSendAckRespBuilder;
@class CMsgSendResp;
@class CMsgSendRespBuilder;


typedef NS_ENUM(SInt32, EConstMsgTypes) {
  EConstMsgTypesMsgTypeNormal = 1,
  EConstMsgTypesMsgTypeAotomsg = 2,
};

BOOL EConstMsgTypesIsValidValue(EConstMsgTypes value);
NSString *NSStringFromEConstMsgTypes(EConstMsgTypes value);

typedef NS_ENUM(SInt32, EConstMsgMediaTypes) {
  EConstMsgMediaTypesMsgMediaTypeText = 1,
  EConstMsgMediaTypesMsgMediaTypeImg = 2,
  EConstMsgMediaTypesMsgMediaTypeAudio = 3,
};

BOOL EConstMsgMediaTypesIsValidValue(EConstMsgMediaTypes value);
NSString *NSStringFromEConstMsgMediaTypes(EConstMsgMediaTypes value);

typedef NS_ENUM(SInt32, EConstPBMsgSendRespCodes) {
  EConstPBMsgSendRespCodesPbMsgSendRespUserBlocked = 402011,
};

BOOL EConstPBMsgSendRespCodesIsValidValue(EConstPBMsgSendRespCodes value);
NSString *NSStringFromEConstPBMsgSendRespCodes(EConstPBMsgSendRespCodes value);


@interface MsgRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface CMsgPBContent : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFromUid_:1;
  BOOL hasToUid_:1;
  BOOL hasTime_:1;
  BOOL hasMsgid_:1;
  BOOL hasMsgData_:1;
  BOOL hasDetail_:1;
  BOOL hasFromSourceType_:1;
  BOOL hasToSourceType_:1;
  BOOL hasMsgType_:1;
  BOOL hasMsgMediaType_:1;
  BOOL hasSyncFlag_:1;
  UInt64 fromUid;
  UInt64 toUid;
  UInt64 time;
  UInt64 msgid;
  NSString* msgData;
  NSString* detail;
  UInt32 fromSourceType;
  UInt32 toSourceType;
  UInt32 msgType;
  UInt32 msgMediaType;
  UInt32 syncFlag;
}
- (BOOL) hasFromSourceType;
- (BOOL) hasToSourceType;
- (BOOL) hasFromUid;
- (BOOL) hasToUid;
- (BOOL) hasTime;
- (BOOL) hasMsgid;
- (BOOL) hasMsgType;
- (BOOL) hasMsgMediaType;
- (BOOL) hasSyncFlag;
- (BOOL) hasMsgData;
- (BOOL) hasDetail;
@property (readonly) UInt32 fromSourceType;
@property (readonly) UInt32 toSourceType;
@property (readonly) UInt64 fromUid;
@property (readonly) UInt64 toUid;
@property (readonly) UInt64 time;
@property (readonly) UInt64 msgid;
@property (readonly) UInt32 msgType;
@property (readonly) UInt32 msgMediaType;
@property (readonly) UInt32 syncFlag;
@property (readonly, strong) NSString* msgData;
@property (readonly, strong) NSString* detail;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgPBContentBuilder*) builder;
+ (CMsgPBContentBuilder*) builder;
+ (CMsgPBContentBuilder*) builderWithPrototype:(CMsgPBContent*) prototype;
- (CMsgPBContentBuilder*) toBuilder;

+ (CMsgPBContent*) parseFromData:(NSData*) data;
+ (CMsgPBContent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgPBContent*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgPBContent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgPBContent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgPBContent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgPBContentBuilder : PBGeneratedMessageBuilder {
@private
  CMsgPBContent* resultCmsgPbcontent;
}

- (CMsgPBContent*) defaultInstance;

- (CMsgPBContentBuilder*) clear;
- (CMsgPBContentBuilder*) clone;

- (CMsgPBContent*) build;
- (CMsgPBContent*) buildPartial;

- (CMsgPBContentBuilder*) mergeFrom:(CMsgPBContent*) other;
- (CMsgPBContentBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgPBContentBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromSourceType;
- (UInt32) fromSourceType;
- (CMsgPBContentBuilder*) setFromSourceType:(UInt32) value;
- (CMsgPBContentBuilder*) clearFromSourceType;

- (BOOL) hasToSourceType;
- (UInt32) toSourceType;
- (CMsgPBContentBuilder*) setToSourceType:(UInt32) value;
- (CMsgPBContentBuilder*) clearToSourceType;

- (BOOL) hasFromUid;
- (UInt64) fromUid;
- (CMsgPBContentBuilder*) setFromUid:(UInt64) value;
- (CMsgPBContentBuilder*) clearFromUid;

- (BOOL) hasToUid;
- (UInt64) toUid;
- (CMsgPBContentBuilder*) setToUid:(UInt64) value;
- (CMsgPBContentBuilder*) clearToUid;

- (BOOL) hasTime;
- (UInt64) time;
- (CMsgPBContentBuilder*) setTime:(UInt64) value;
- (CMsgPBContentBuilder*) clearTime;

- (BOOL) hasMsgid;
- (UInt64) msgid;
- (CMsgPBContentBuilder*) setMsgid:(UInt64) value;
- (CMsgPBContentBuilder*) clearMsgid;

- (BOOL) hasMsgType;
- (UInt32) msgType;
- (CMsgPBContentBuilder*) setMsgType:(UInt32) value;
- (CMsgPBContentBuilder*) clearMsgType;

- (BOOL) hasMsgMediaType;
- (UInt32) msgMediaType;
- (CMsgPBContentBuilder*) setMsgMediaType:(UInt32) value;
- (CMsgPBContentBuilder*) clearMsgMediaType;

- (BOOL) hasSyncFlag;
- (UInt32) syncFlag;
- (CMsgPBContentBuilder*) setSyncFlag:(UInt32) value;
- (CMsgPBContentBuilder*) clearSyncFlag;

- (BOOL) hasMsgData;
- (NSString*) msgData;
- (CMsgPBContentBuilder*) setMsgData:(NSString*) value;
- (CMsgPBContentBuilder*) clearMsgData;

- (BOOL) hasDetail;
- (NSString*) detail;
- (CMsgPBContentBuilder*) setDetail:(NSString*) value;
- (CMsgPBContentBuilder*) clearDetail;
@end

@interface CMsgSendResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgSendRespBuilder*) builder;
+ (CMsgSendRespBuilder*) builder;
+ (CMsgSendRespBuilder*) builderWithPrototype:(CMsgSendResp*) prototype;
- (CMsgSendRespBuilder*) toBuilder;

+ (CMsgSendResp*) parseFromData:(NSData*) data;
+ (CMsgSendResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSendResp*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgSendResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSendResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgSendResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgSendRespBuilder : PBGeneratedMessageBuilder {
@private
  CMsgSendResp* resultCmsgSendResp;
}

- (CMsgSendResp*) defaultInstance;

- (CMsgSendRespBuilder*) clear;
- (CMsgSendRespBuilder*) clone;

- (CMsgSendResp*) build;
- (CMsgSendResp*) buildPartial;

- (CMsgSendRespBuilder*) mergeFrom:(CMsgSendResp*) other;
- (CMsgSendRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgSendRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgAckContent : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAckUid_:1;
  BOOL hasAckMsgid_:1;
  BOOL hasAckSourceType_:1;
  UInt64 ackUid;
  UInt64 ackMsgid;
  UInt32 ackSourceType;
}
- (BOOL) hasAckSourceType;
- (BOOL) hasAckUid;
- (BOOL) hasAckMsgid;
@property (readonly) UInt32 ackSourceType;
@property (readonly) UInt64 ackUid;
@property (readonly) UInt64 ackMsgid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgAckContentBuilder*) builder;
+ (CMsgAckContentBuilder*) builder;
+ (CMsgAckContentBuilder*) builderWithPrototype:(CMsgAckContent*) prototype;
- (CMsgAckContentBuilder*) toBuilder;

+ (CMsgAckContent*) parseFromData:(NSData*) data;
+ (CMsgAckContent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgAckContent*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgAckContent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgAckContent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgAckContent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgAckContentBuilder : PBGeneratedMessageBuilder {
@private
  CMsgAckContent* resultCmsgAckContent;
}

- (CMsgAckContent*) defaultInstance;

- (CMsgAckContentBuilder*) clear;
- (CMsgAckContentBuilder*) clone;

- (CMsgAckContent*) build;
- (CMsgAckContent*) buildPartial;

- (CMsgAckContentBuilder*) mergeFrom:(CMsgAckContent*) other;
- (CMsgAckContentBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgAckContentBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAckSourceType;
- (UInt32) ackSourceType;
- (CMsgAckContentBuilder*) setAckSourceType:(UInt32) value;
- (CMsgAckContentBuilder*) clearAckSourceType;

- (BOOL) hasAckUid;
- (UInt64) ackUid;
- (CMsgAckContentBuilder*) setAckUid:(UInt64) value;
- (CMsgAckContentBuilder*) clearAckUid;

- (BOOL) hasAckMsgid;
- (UInt64) ackMsgid;
- (CMsgAckContentBuilder*) setAckMsgid:(UInt64) value;
- (CMsgAckContentBuilder*) clearAckMsgid;
@end

@interface CMsgSendAckResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgSendAckRespBuilder*) builder;
+ (CMsgSendAckRespBuilder*) builder;
+ (CMsgSendAckRespBuilder*) builderWithPrototype:(CMsgSendAckResp*) prototype;
- (CMsgSendAckRespBuilder*) toBuilder;

+ (CMsgSendAckResp*) parseFromData:(NSData*) data;
+ (CMsgSendAckResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSendAckResp*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgSendAckResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgSendAckResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgSendAckResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgSendAckRespBuilder : PBGeneratedMessageBuilder {
@private
  CMsgSendAckResp* resultCmsgSendAckResp;
}

- (CMsgSendAckResp*) defaultInstance;

- (CMsgSendAckRespBuilder*) clear;
- (CMsgSendAckRespBuilder*) clone;

- (CMsgSendAckResp*) build;
- (CMsgSendAckResp*) buildPartial;

- (CMsgSendAckRespBuilder*) mergeFrom:(CMsgSendAckResp*) other;
- (CMsgSendAckRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgSendAckRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgCommonReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFromUid_:1;
  BOOL hasToUid_:1;
  BOOL hasTime_:1;
  BOOL hasMsgid_:1;
  BOOL hasMsgData_:1;
  BOOL hasFromSourceType_:1;
  BOOL hasMsgType_:1;
  UInt64 fromUid;
  UInt64 toUid;
  UInt64 time;
  UInt64 msgid;
  NSData* msgData;
  UInt32 fromSourceType;
  UInt32 msgType;
}
- (BOOL) hasFromSourceType;
- (BOOL) hasFromUid;
- (BOOL) hasToUid;
- (BOOL) hasTime;
- (BOOL) hasMsgid;
- (BOOL) hasMsgType;
- (BOOL) hasMsgData;
@property (readonly) UInt32 fromSourceType;
@property (readonly) UInt64 fromUid;
@property (readonly) UInt64 toUid;
@property (readonly) UInt64 time;
@property (readonly) UInt64 msgid;
@property (readonly) UInt32 msgType;
@property (readonly, strong) NSData* msgData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgCommonReqBuilder*) builder;
+ (CMsgCommonReqBuilder*) builder;
+ (CMsgCommonReqBuilder*) builderWithPrototype:(CMsgCommonReq*) prototype;
- (CMsgCommonReqBuilder*) toBuilder;

+ (CMsgCommonReq*) parseFromData:(NSData*) data;
+ (CMsgCommonReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgCommonReq*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgCommonReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgCommonReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgCommonReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgCommonReqBuilder : PBGeneratedMessageBuilder {
@private
  CMsgCommonReq* resultCmsgCommonReq;
}

- (CMsgCommonReq*) defaultInstance;

- (CMsgCommonReqBuilder*) clear;
- (CMsgCommonReqBuilder*) clone;

- (CMsgCommonReq*) build;
- (CMsgCommonReq*) buildPartial;

- (CMsgCommonReqBuilder*) mergeFrom:(CMsgCommonReq*) other;
- (CMsgCommonReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgCommonReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromSourceType;
- (UInt32) fromSourceType;
- (CMsgCommonReqBuilder*) setFromSourceType:(UInt32) value;
- (CMsgCommonReqBuilder*) clearFromSourceType;

- (BOOL) hasFromUid;
- (UInt64) fromUid;
- (CMsgCommonReqBuilder*) setFromUid:(UInt64) value;
- (CMsgCommonReqBuilder*) clearFromUid;

- (BOOL) hasToUid;
- (UInt64) toUid;
- (CMsgCommonReqBuilder*) setToUid:(UInt64) value;
- (CMsgCommonReqBuilder*) clearToUid;

- (BOOL) hasTime;
- (UInt64) time;
- (CMsgCommonReqBuilder*) setTime:(UInt64) value;
- (CMsgCommonReqBuilder*) clearTime;

- (BOOL) hasMsgid;
- (UInt64) msgid;
- (CMsgCommonReqBuilder*) setMsgid:(UInt64) value;
- (CMsgCommonReqBuilder*) clearMsgid;

- (BOOL) hasMsgType;
- (UInt32) msgType;
- (CMsgCommonReqBuilder*) setMsgType:(UInt32) value;
- (CMsgCommonReqBuilder*) clearMsgType;

- (BOOL) hasMsgData;
- (NSData*) msgData;
- (CMsgCommonReqBuilder*) setMsgData:(NSData*) value;
- (CMsgCommonReqBuilder*) clearMsgData;
@end

@interface CMsgCommonResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgCommonRespBuilder*) builder;
+ (CMsgCommonRespBuilder*) builder;
+ (CMsgCommonRespBuilder*) builderWithPrototype:(CMsgCommonResp*) prototype;
- (CMsgCommonRespBuilder*) toBuilder;

+ (CMsgCommonResp*) parseFromData:(NSData*) data;
+ (CMsgCommonResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgCommonResp*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgCommonResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgCommonResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgCommonResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgCommonRespBuilder : PBGeneratedMessageBuilder {
@private
  CMsgCommonResp* resultCmsgCommonResp;
}

- (CMsgCommonResp*) defaultInstance;

- (CMsgCommonRespBuilder*) clear;
- (CMsgCommonRespBuilder*) clone;

- (CMsgCommonResp*) build;
- (CMsgCommonResp*) buildPartial;

- (CMsgCommonRespBuilder*) mergeFrom:(CMsgCommonResp*) other;
- (CMsgCommonRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgCommonRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetOfflineMsgReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStartMsgid_:1;
  BOOL hasStartTime_:1;
  BOOL hasMsgType_:1;
  BOOL hasLimit_:1;
  UInt64 startMsgid;
  UInt64 startTime;
  UInt32 msgType;
  UInt32 limit;
}
- (BOOL) hasMsgType;
- (BOOL) hasLimit;
- (BOOL) hasStartMsgid;
- (BOOL) hasStartTime;
@property (readonly) UInt32 msgType;
@property (readonly) UInt32 limit;
@property (readonly) UInt64 startMsgid;
@property (readonly) UInt64 startTime;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgGetOfflineMsgReqBuilder*) builder;
+ (CMsgGetOfflineMsgReqBuilder*) builder;
+ (CMsgGetOfflineMsgReqBuilder*) builderWithPrototype:(CMsgGetOfflineMsgReq*) prototype;
- (CMsgGetOfflineMsgReqBuilder*) toBuilder;

+ (CMsgGetOfflineMsgReq*) parseFromData:(NSData*) data;
+ (CMsgGetOfflineMsgReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineMsgReq*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgGetOfflineMsgReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgGetOfflineMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetOfflineMsgReqBuilder : PBGeneratedMessageBuilder {
@private
  CMsgGetOfflineMsgReq* resultCmsgGetOfflineMsgReq;
}

- (CMsgGetOfflineMsgReq*) defaultInstance;

- (CMsgGetOfflineMsgReqBuilder*) clear;
- (CMsgGetOfflineMsgReqBuilder*) clone;

- (CMsgGetOfflineMsgReq*) build;
- (CMsgGetOfflineMsgReq*) buildPartial;

- (CMsgGetOfflineMsgReqBuilder*) mergeFrom:(CMsgGetOfflineMsgReq*) other;
- (CMsgGetOfflineMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgGetOfflineMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMsgType;
- (UInt32) msgType;
- (CMsgGetOfflineMsgReqBuilder*) setMsgType:(UInt32) value;
- (CMsgGetOfflineMsgReqBuilder*) clearMsgType;

- (BOOL) hasLimit;
- (UInt32) limit;
- (CMsgGetOfflineMsgReqBuilder*) setLimit:(UInt32) value;
- (CMsgGetOfflineMsgReqBuilder*) clearLimit;

- (BOOL) hasStartMsgid;
- (UInt64) startMsgid;
- (CMsgGetOfflineMsgReqBuilder*) setStartMsgid:(UInt64) value;
- (CMsgGetOfflineMsgReqBuilder*) clearStartMsgid;

- (BOOL) hasStartTime;
- (UInt64) startTime;
- (CMsgGetOfflineMsgReqBuilder*) setStartTime:(UInt64) value;
- (CMsgGetOfflineMsgReqBuilder*) clearStartTime;
@end

@interface CMsgGetOfflineMsgResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLastMsgid_:1;
  BOOL hasLastTime_:1;
  BOOL hasMsgType_:1;
  UInt64 lastMsgid;
  UInt64 lastTime;
  UInt32 msgType;
  NSMutableArray * msgsArray;
}
- (BOOL) hasMsgType;
- (BOOL) hasLastMsgid;
- (BOOL) hasLastTime;
@property (readonly, strong) NSArray * msgs;
@property (readonly) UInt32 msgType;
@property (readonly) UInt64 lastMsgid;
@property (readonly) UInt64 lastTime;
- (NSData*)msgsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgGetOfflineMsgRespBuilder*) builder;
+ (CMsgGetOfflineMsgRespBuilder*) builder;
+ (CMsgGetOfflineMsgRespBuilder*) builderWithPrototype:(CMsgGetOfflineMsgResp*) prototype;
- (CMsgGetOfflineMsgRespBuilder*) toBuilder;

+ (CMsgGetOfflineMsgResp*) parseFromData:(NSData*) data;
+ (CMsgGetOfflineMsgResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineMsgResp*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgGetOfflineMsgResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineMsgResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgGetOfflineMsgResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetOfflineMsgRespBuilder : PBGeneratedMessageBuilder {
@private
  CMsgGetOfflineMsgResp* resultCmsgGetOfflineMsgResp;
}

- (CMsgGetOfflineMsgResp*) defaultInstance;

- (CMsgGetOfflineMsgRespBuilder*) clear;
- (CMsgGetOfflineMsgRespBuilder*) clone;

- (CMsgGetOfflineMsgResp*) build;
- (CMsgGetOfflineMsgResp*) buildPartial;

- (CMsgGetOfflineMsgRespBuilder*) mergeFrom:(CMsgGetOfflineMsgResp*) other;
- (CMsgGetOfflineMsgRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgGetOfflineMsgRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)msgs;
- (NSData*)msgsAtIndex:(NSUInteger)index;
- (CMsgGetOfflineMsgRespBuilder *)addMsgs:(NSData*)value;
- (CMsgGetOfflineMsgRespBuilder *)setMsgsArray:(NSArray *)array;
- (CMsgGetOfflineMsgRespBuilder *)clearMsgs;

- (BOOL) hasMsgType;
- (UInt32) msgType;
- (CMsgGetOfflineMsgRespBuilder*) setMsgType:(UInt32) value;
- (CMsgGetOfflineMsgRespBuilder*) clearMsgType;

- (BOOL) hasLastMsgid;
- (UInt64) lastMsgid;
- (CMsgGetOfflineMsgRespBuilder*) setLastMsgid:(UInt64) value;
- (CMsgGetOfflineMsgRespBuilder*) clearLastMsgid;

- (BOOL) hasLastTime;
- (UInt64) lastTime;
- (CMsgGetOfflineMsgRespBuilder*) setLastTime:(UInt64) value;
- (CMsgGetOfflineMsgRespBuilder*) clearLastTime;
@end

@interface CMsgGetOfflineMsgAckReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAckMsgId_:1;
  BOOL hasMsgType_:1;
  UInt64 ackMsgId;
  UInt32 msgType;
}
- (BOOL) hasMsgType;
- (BOOL) hasAckMsgId;
@property (readonly) UInt32 msgType;
@property (readonly) UInt64 ackMsgId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgGetOfflineMsgAckReqBuilder*) builder;
+ (CMsgGetOfflineMsgAckReqBuilder*) builder;
+ (CMsgGetOfflineMsgAckReqBuilder*) builderWithPrototype:(CMsgGetOfflineMsgAckReq*) prototype;
- (CMsgGetOfflineMsgAckReqBuilder*) toBuilder;

+ (CMsgGetOfflineMsgAckReq*) parseFromData:(NSData*) data;
+ (CMsgGetOfflineMsgAckReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineMsgAckReq*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgGetOfflineMsgAckReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineMsgAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgGetOfflineMsgAckReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetOfflineMsgAckReqBuilder : PBGeneratedMessageBuilder {
@private
  CMsgGetOfflineMsgAckReq* resultCmsgGetOfflineMsgAckReq;
}

- (CMsgGetOfflineMsgAckReq*) defaultInstance;

- (CMsgGetOfflineMsgAckReqBuilder*) clear;
- (CMsgGetOfflineMsgAckReqBuilder*) clone;

- (CMsgGetOfflineMsgAckReq*) build;
- (CMsgGetOfflineMsgAckReq*) buildPartial;

- (CMsgGetOfflineMsgAckReqBuilder*) mergeFrom:(CMsgGetOfflineMsgAckReq*) other;
- (CMsgGetOfflineMsgAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgGetOfflineMsgAckReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMsgType;
- (UInt32) msgType;
- (CMsgGetOfflineMsgAckReqBuilder*) setMsgType:(UInt32) value;
- (CMsgGetOfflineMsgAckReqBuilder*) clearMsgType;

- (BOOL) hasAckMsgId;
- (UInt64) ackMsgId;
- (CMsgGetOfflineMsgAckReqBuilder*) setAckMsgId:(UInt64) value;
- (CMsgGetOfflineMsgAckReqBuilder*) clearAckMsgId;
@end

@interface CMsgGetOfflineMsgAckResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgGetOfflineMsgAckRespBuilder*) builder;
+ (CMsgGetOfflineMsgAckRespBuilder*) builder;
+ (CMsgGetOfflineMsgAckRespBuilder*) builderWithPrototype:(CMsgGetOfflineMsgAckResp*) prototype;
- (CMsgGetOfflineMsgAckRespBuilder*) toBuilder;

+ (CMsgGetOfflineMsgAckResp*) parseFromData:(NSData*) data;
+ (CMsgGetOfflineMsgAckResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineMsgAckResp*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgGetOfflineMsgAckResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineMsgAckResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgGetOfflineMsgAckResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetOfflineMsgAckRespBuilder : PBGeneratedMessageBuilder {
@private
  CMsgGetOfflineMsgAckResp* resultCmsgGetOfflineMsgAckResp;
}

- (CMsgGetOfflineMsgAckResp*) defaultInstance;

- (CMsgGetOfflineMsgAckRespBuilder*) clear;
- (CMsgGetOfflineMsgAckRespBuilder*) clone;

- (CMsgGetOfflineMsgAckResp*) build;
- (CMsgGetOfflineMsgAckResp*) buildPartial;

- (CMsgGetOfflineMsgAckRespBuilder*) mergeFrom:(CMsgGetOfflineMsgAckResp*) other;
- (CMsgGetOfflineMsgAckRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgGetOfflineMsgAckRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgClearOfflineByUidReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  BOOL hasMsgType_:1;
  UInt64 uid;
  UInt32 msgType;
}
- (BOOL) hasUid;
- (BOOL) hasMsgType;
@property (readonly) UInt64 uid;
@property (readonly) UInt32 msgType;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgClearOfflineByUidReqBuilder*) builder;
+ (CMsgClearOfflineByUidReqBuilder*) builder;
+ (CMsgClearOfflineByUidReqBuilder*) builderWithPrototype:(CMsgClearOfflineByUidReq*) prototype;
- (CMsgClearOfflineByUidReqBuilder*) toBuilder;

+ (CMsgClearOfflineByUidReq*) parseFromData:(NSData*) data;
+ (CMsgClearOfflineByUidReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgClearOfflineByUidReq*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgClearOfflineByUidReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgClearOfflineByUidReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgClearOfflineByUidReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgClearOfflineByUidReqBuilder : PBGeneratedMessageBuilder {
@private
  CMsgClearOfflineByUidReq* resultCmsgClearOfflineByUidReq;
}

- (CMsgClearOfflineByUidReq*) defaultInstance;

- (CMsgClearOfflineByUidReqBuilder*) clear;
- (CMsgClearOfflineByUidReqBuilder*) clone;

- (CMsgClearOfflineByUidReq*) build;
- (CMsgClearOfflineByUidReq*) buildPartial;

- (CMsgClearOfflineByUidReqBuilder*) mergeFrom:(CMsgClearOfflineByUidReq*) other;
- (CMsgClearOfflineByUidReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgClearOfflineByUidReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt64) uid;
- (CMsgClearOfflineByUidReqBuilder*) setUid:(UInt64) value;
- (CMsgClearOfflineByUidReqBuilder*) clearUid;

- (BOOL) hasMsgType;
- (UInt32) msgType;
- (CMsgClearOfflineByUidReqBuilder*) setMsgType:(UInt32) value;
- (CMsgClearOfflineByUidReqBuilder*) clearMsgType;
@end

@interface CMsgClearOfflineByUidResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgClearOfflineByUidRespBuilder*) builder;
+ (CMsgClearOfflineByUidRespBuilder*) builder;
+ (CMsgClearOfflineByUidRespBuilder*) builderWithPrototype:(CMsgClearOfflineByUidResp*) prototype;
- (CMsgClearOfflineByUidRespBuilder*) toBuilder;

+ (CMsgClearOfflineByUidResp*) parseFromData:(NSData*) data;
+ (CMsgClearOfflineByUidResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgClearOfflineByUidResp*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgClearOfflineByUidResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgClearOfflineByUidResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgClearOfflineByUidResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgClearOfflineByUidRespBuilder : PBGeneratedMessageBuilder {
@private
  CMsgClearOfflineByUidResp* resultCmsgClearOfflineByUidResp;
}

- (CMsgClearOfflineByUidResp*) defaultInstance;

- (CMsgClearOfflineByUidRespBuilder*) clear;
- (CMsgClearOfflineByUidRespBuilder*) clone;

- (CMsgClearOfflineByUidResp*) build;
- (CMsgClearOfflineByUidResp*) buildPartial;

- (CMsgClearOfflineByUidRespBuilder*) mergeFrom:(CMsgClearOfflineByUidResp*) other;
- (CMsgClearOfflineByUidRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgClearOfflineByUidRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetOfflineCountByUidReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMsgType_:1;
  UInt32 msgType;
  PBAppendableArray * uidsArray;
}
- (BOOL) hasMsgType;
@property (readonly, strong) PBArray * uids;
@property (readonly) UInt32 msgType;
- (UInt64)uidsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgGetOfflineCountByUidReqBuilder*) builder;
+ (CMsgGetOfflineCountByUidReqBuilder*) builder;
+ (CMsgGetOfflineCountByUidReqBuilder*) builderWithPrototype:(CMsgGetOfflineCountByUidReq*) prototype;
- (CMsgGetOfflineCountByUidReqBuilder*) toBuilder;

+ (CMsgGetOfflineCountByUidReq*) parseFromData:(NSData*) data;
+ (CMsgGetOfflineCountByUidReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineCountByUidReq*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgGetOfflineCountByUidReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineCountByUidReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgGetOfflineCountByUidReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetOfflineCountByUidReqBuilder : PBGeneratedMessageBuilder {
@private
  CMsgGetOfflineCountByUidReq* resultCmsgGetOfflineCountByUidReq;
}

- (CMsgGetOfflineCountByUidReq*) defaultInstance;

- (CMsgGetOfflineCountByUidReqBuilder*) clear;
- (CMsgGetOfflineCountByUidReqBuilder*) clone;

- (CMsgGetOfflineCountByUidReq*) build;
- (CMsgGetOfflineCountByUidReq*) buildPartial;

- (CMsgGetOfflineCountByUidReqBuilder*) mergeFrom:(CMsgGetOfflineCountByUidReq*) other;
- (CMsgGetOfflineCountByUidReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgGetOfflineCountByUidReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)uids;
- (UInt64)uidsAtIndex:(NSUInteger)index;
- (CMsgGetOfflineCountByUidReqBuilder *)addUids:(UInt64)value;
- (CMsgGetOfflineCountByUidReqBuilder *)setUidsArray:(NSArray *)array;
- (CMsgGetOfflineCountByUidReqBuilder *)setUidsValues:(const UInt64 *)values count:(NSUInteger)count;
- (CMsgGetOfflineCountByUidReqBuilder *)clearUids;

- (BOOL) hasMsgType;
- (UInt32) msgType;
- (CMsgGetOfflineCountByUidReqBuilder*) setMsgType:(UInt32) value;
- (CMsgGetOfflineCountByUidReqBuilder*) clearMsgType;
@end

@interface CMsgOfflineCountInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  BOOL hasCount_:1;
  UInt64 uid;
  UInt32 count;
}
- (BOOL) hasUid;
- (BOOL) hasCount;
@property (readonly) UInt64 uid;
@property (readonly) UInt32 count;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgOfflineCountInfoBuilder*) builder;
+ (CMsgOfflineCountInfoBuilder*) builder;
+ (CMsgOfflineCountInfoBuilder*) builderWithPrototype:(CMsgOfflineCountInfo*) prototype;
- (CMsgOfflineCountInfoBuilder*) toBuilder;

+ (CMsgOfflineCountInfo*) parseFromData:(NSData*) data;
+ (CMsgOfflineCountInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgOfflineCountInfo*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgOfflineCountInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgOfflineCountInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgOfflineCountInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgOfflineCountInfoBuilder : PBGeneratedMessageBuilder {
@private
  CMsgOfflineCountInfo* resultCmsgOfflineCountInfo;
}

- (CMsgOfflineCountInfo*) defaultInstance;

- (CMsgOfflineCountInfoBuilder*) clear;
- (CMsgOfflineCountInfoBuilder*) clone;

- (CMsgOfflineCountInfo*) build;
- (CMsgOfflineCountInfo*) buildPartial;

- (CMsgOfflineCountInfoBuilder*) mergeFrom:(CMsgOfflineCountInfo*) other;
- (CMsgOfflineCountInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgOfflineCountInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt64) uid;
- (CMsgOfflineCountInfoBuilder*) setUid:(UInt64) value;
- (CMsgOfflineCountInfoBuilder*) clearUid;

- (BOOL) hasCount;
- (UInt32) count;
- (CMsgOfflineCountInfoBuilder*) setCount:(UInt32) value;
- (CMsgOfflineCountInfoBuilder*) clearCount;
@end

@interface CMsgGetOfflineCountByUidResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * countInfosArray;
}
@property (readonly, strong) NSArray * countInfos;
- (CMsgOfflineCountInfo*)countInfosAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgGetOfflineCountByUidRespBuilder*) builder;
+ (CMsgGetOfflineCountByUidRespBuilder*) builder;
+ (CMsgGetOfflineCountByUidRespBuilder*) builderWithPrototype:(CMsgGetOfflineCountByUidResp*) prototype;
- (CMsgGetOfflineCountByUidRespBuilder*) toBuilder;

+ (CMsgGetOfflineCountByUidResp*) parseFromData:(NSData*) data;
+ (CMsgGetOfflineCountByUidResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineCountByUidResp*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgGetOfflineCountByUidResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineCountByUidResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgGetOfflineCountByUidResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetOfflineCountByUidRespBuilder : PBGeneratedMessageBuilder {
@private
  CMsgGetOfflineCountByUidResp* resultCmsgGetOfflineCountByUidResp;
}

- (CMsgGetOfflineCountByUidResp*) defaultInstance;

- (CMsgGetOfflineCountByUidRespBuilder*) clear;
- (CMsgGetOfflineCountByUidRespBuilder*) clone;

- (CMsgGetOfflineCountByUidResp*) build;
- (CMsgGetOfflineCountByUidResp*) buildPartial;

- (CMsgGetOfflineCountByUidRespBuilder*) mergeFrom:(CMsgGetOfflineCountByUidResp*) other;
- (CMsgGetOfflineCountByUidRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgGetOfflineCountByUidRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)countInfos;
- (CMsgOfflineCountInfo*)countInfosAtIndex:(NSUInteger)index;
- (CMsgGetOfflineCountByUidRespBuilder *)addCountInfos:(CMsgOfflineCountInfo*)value;
- (CMsgGetOfflineCountByUidRespBuilder *)setCountInfosArray:(NSArray *)array;
- (CMsgGetOfflineCountByUidRespBuilder *)clearCountInfos;
@end

@interface CMsgGetOfflineCountReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgGetOfflineCountReqBuilder*) builder;
+ (CMsgGetOfflineCountReqBuilder*) builder;
+ (CMsgGetOfflineCountReqBuilder*) builderWithPrototype:(CMsgGetOfflineCountReq*) prototype;
- (CMsgGetOfflineCountReqBuilder*) toBuilder;

+ (CMsgGetOfflineCountReq*) parseFromData:(NSData*) data;
+ (CMsgGetOfflineCountReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineCountReq*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgGetOfflineCountReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineCountReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgGetOfflineCountReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetOfflineCountReqBuilder : PBGeneratedMessageBuilder {
@private
  CMsgGetOfflineCountReq* resultCmsgGetOfflineCountReq;
}

- (CMsgGetOfflineCountReq*) defaultInstance;

- (CMsgGetOfflineCountReqBuilder*) clear;
- (CMsgGetOfflineCountReqBuilder*) clone;

- (CMsgGetOfflineCountReq*) build;
- (CMsgGetOfflineCountReq*) buildPartial;

- (CMsgGetOfflineCountReqBuilder*) mergeFrom:(CMsgGetOfflineCountReq*) other;
- (CMsgGetOfflineCountReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgGetOfflineCountReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetOfflineCountResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMsgCount_:1;
  UInt32 msgCount;
}
- (BOOL) hasMsgCount;
@property (readonly) UInt32 msgCount;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgGetOfflineCountRespBuilder*) builder;
+ (CMsgGetOfflineCountRespBuilder*) builder;
+ (CMsgGetOfflineCountRespBuilder*) builderWithPrototype:(CMsgGetOfflineCountResp*) prototype;
- (CMsgGetOfflineCountRespBuilder*) toBuilder;

+ (CMsgGetOfflineCountResp*) parseFromData:(NSData*) data;
+ (CMsgGetOfflineCountResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineCountResp*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgGetOfflineCountResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetOfflineCountResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgGetOfflineCountResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetOfflineCountRespBuilder : PBGeneratedMessageBuilder {
@private
  CMsgGetOfflineCountResp* resultCmsgGetOfflineCountResp;
}

- (CMsgGetOfflineCountResp*) defaultInstance;

- (CMsgGetOfflineCountRespBuilder*) clear;
- (CMsgGetOfflineCountRespBuilder*) clone;

- (CMsgGetOfflineCountResp*) build;
- (CMsgGetOfflineCountResp*) buildPartial;

- (CMsgGetOfflineCountRespBuilder*) mergeFrom:(CMsgGetOfflineCountResp*) other;
- (CMsgGetOfflineCountRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgGetOfflineCountRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMsgCount;
- (UInt32) msgCount;
- (CMsgGetOfflineCountRespBuilder*) setMsgCount:(UInt32) value;
- (CMsgGetOfflineCountRespBuilder*) clearMsgCount;
@end

@interface CMsgGetHistoryMsgReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  BOOL hasStartMsgtime_:1;
  BOOL hasStartMsgid_:1;
  BOOL hasLimit_:1;
  UInt64 uid;
  UInt64 startMsgtime;
  UInt64 startMsgid;
  UInt32 limit;
}
- (BOOL) hasUid;
- (BOOL) hasLimit;
- (BOOL) hasStartMsgtime;
- (BOOL) hasStartMsgid;
@property (readonly) UInt64 uid;
@property (readonly) UInt32 limit;
@property (readonly) UInt64 startMsgtime;
@property (readonly) UInt64 startMsgid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgGetHistoryMsgReqBuilder*) builder;
+ (CMsgGetHistoryMsgReqBuilder*) builder;
+ (CMsgGetHistoryMsgReqBuilder*) builderWithPrototype:(CMsgGetHistoryMsgReq*) prototype;
- (CMsgGetHistoryMsgReqBuilder*) toBuilder;

+ (CMsgGetHistoryMsgReq*) parseFromData:(NSData*) data;
+ (CMsgGetHistoryMsgReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetHistoryMsgReq*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgGetHistoryMsgReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetHistoryMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgGetHistoryMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetHistoryMsgReqBuilder : PBGeneratedMessageBuilder {
@private
  CMsgGetHistoryMsgReq* resultCmsgGetHistoryMsgReq;
}

- (CMsgGetHistoryMsgReq*) defaultInstance;

- (CMsgGetHistoryMsgReqBuilder*) clear;
- (CMsgGetHistoryMsgReqBuilder*) clone;

- (CMsgGetHistoryMsgReq*) build;
- (CMsgGetHistoryMsgReq*) buildPartial;

- (CMsgGetHistoryMsgReqBuilder*) mergeFrom:(CMsgGetHistoryMsgReq*) other;
- (CMsgGetHistoryMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgGetHistoryMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt64) uid;
- (CMsgGetHistoryMsgReqBuilder*) setUid:(UInt64) value;
- (CMsgGetHistoryMsgReqBuilder*) clearUid;

- (BOOL) hasLimit;
- (UInt32) limit;
- (CMsgGetHistoryMsgReqBuilder*) setLimit:(UInt32) value;
- (CMsgGetHistoryMsgReqBuilder*) clearLimit;

- (BOOL) hasStartMsgtime;
- (UInt64) startMsgtime;
- (CMsgGetHistoryMsgReqBuilder*) setStartMsgtime:(UInt64) value;
- (CMsgGetHistoryMsgReqBuilder*) clearStartMsgtime;

- (BOOL) hasStartMsgid;
- (UInt64) startMsgid;
- (CMsgGetHistoryMsgReqBuilder*) setStartMsgid:(UInt64) value;
- (CMsgGetHistoryMsgReqBuilder*) clearStartMsgid;
@end

@interface CMsgGetHistoryMsgResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLastMsgtime_:1;
  BOOL hasLastMsgid_:1;
  UInt64 lastMsgtime;
  UInt64 lastMsgid;
  NSMutableArray * msgsArray;
}
- (BOOL) hasLastMsgtime;
- (BOOL) hasLastMsgid;
@property (readonly, strong) NSArray * msgs;
@property (readonly) UInt64 lastMsgtime;
@property (readonly) UInt64 lastMsgid;
- (CMsgPBContent*)msgsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgGetHistoryMsgRespBuilder*) builder;
+ (CMsgGetHistoryMsgRespBuilder*) builder;
+ (CMsgGetHistoryMsgRespBuilder*) builderWithPrototype:(CMsgGetHistoryMsgResp*) prototype;
- (CMsgGetHistoryMsgRespBuilder*) toBuilder;

+ (CMsgGetHistoryMsgResp*) parseFromData:(NSData*) data;
+ (CMsgGetHistoryMsgResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetHistoryMsgResp*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgGetHistoryMsgResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetHistoryMsgResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgGetHistoryMsgResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetHistoryMsgRespBuilder : PBGeneratedMessageBuilder {
@private
  CMsgGetHistoryMsgResp* resultCmsgGetHistoryMsgResp;
}

- (CMsgGetHistoryMsgResp*) defaultInstance;

- (CMsgGetHistoryMsgRespBuilder*) clear;
- (CMsgGetHistoryMsgRespBuilder*) clone;

- (CMsgGetHistoryMsgResp*) build;
- (CMsgGetHistoryMsgResp*) buildPartial;

- (CMsgGetHistoryMsgRespBuilder*) mergeFrom:(CMsgGetHistoryMsgResp*) other;
- (CMsgGetHistoryMsgRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgGetHistoryMsgRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)msgs;
- (CMsgPBContent*)msgsAtIndex:(NSUInteger)index;
- (CMsgGetHistoryMsgRespBuilder *)addMsgs:(CMsgPBContent*)value;
- (CMsgGetHistoryMsgRespBuilder *)setMsgsArray:(NSArray *)array;
- (CMsgGetHistoryMsgRespBuilder *)clearMsgs;

- (BOOL) hasLastMsgtime;
- (UInt64) lastMsgtime;
- (CMsgGetHistoryMsgRespBuilder*) setLastMsgtime:(UInt64) value;
- (CMsgGetHistoryMsgRespBuilder*) clearLastMsgtime;

- (BOOL) hasLastMsgid;
- (UInt64) lastMsgid;
- (CMsgGetHistoryMsgRespBuilder*) setLastMsgid:(UInt64) value;
- (CMsgGetHistoryMsgRespBuilder*) clearLastMsgid;
@end

@interface CMsgGetLatestMsgReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  BOOL hasStartMsgtime_:1;
  BOOL hasStartMsgid_:1;
  BOOL hasLimit_:1;
  UInt64 uid;
  UInt64 startMsgtime;
  UInt64 startMsgid;
  UInt32 limit;
}
- (BOOL) hasUid;
- (BOOL) hasLimit;
- (BOOL) hasStartMsgtime;
- (BOOL) hasStartMsgid;
@property (readonly) UInt64 uid;
@property (readonly) UInt32 limit;
@property (readonly) UInt64 startMsgtime;
@property (readonly) UInt64 startMsgid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgGetLatestMsgReqBuilder*) builder;
+ (CMsgGetLatestMsgReqBuilder*) builder;
+ (CMsgGetLatestMsgReqBuilder*) builderWithPrototype:(CMsgGetLatestMsgReq*) prototype;
- (CMsgGetLatestMsgReqBuilder*) toBuilder;

+ (CMsgGetLatestMsgReq*) parseFromData:(NSData*) data;
+ (CMsgGetLatestMsgReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetLatestMsgReq*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgGetLatestMsgReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetLatestMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgGetLatestMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetLatestMsgReqBuilder : PBGeneratedMessageBuilder {
@private
  CMsgGetLatestMsgReq* resultCmsgGetLatestMsgReq;
}

- (CMsgGetLatestMsgReq*) defaultInstance;

- (CMsgGetLatestMsgReqBuilder*) clear;
- (CMsgGetLatestMsgReqBuilder*) clone;

- (CMsgGetLatestMsgReq*) build;
- (CMsgGetLatestMsgReq*) buildPartial;

- (CMsgGetLatestMsgReqBuilder*) mergeFrom:(CMsgGetLatestMsgReq*) other;
- (CMsgGetLatestMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgGetLatestMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt64) uid;
- (CMsgGetLatestMsgReqBuilder*) setUid:(UInt64) value;
- (CMsgGetLatestMsgReqBuilder*) clearUid;

- (BOOL) hasLimit;
- (UInt32) limit;
- (CMsgGetLatestMsgReqBuilder*) setLimit:(UInt32) value;
- (CMsgGetLatestMsgReqBuilder*) clearLimit;

- (BOOL) hasStartMsgtime;
- (UInt64) startMsgtime;
- (CMsgGetLatestMsgReqBuilder*) setStartMsgtime:(UInt64) value;
- (CMsgGetLatestMsgReqBuilder*) clearStartMsgtime;

- (BOOL) hasStartMsgid;
- (UInt64) startMsgid;
- (CMsgGetLatestMsgReqBuilder*) setStartMsgid:(UInt64) value;
- (CMsgGetLatestMsgReqBuilder*) clearStartMsgid;
@end

@interface CMsgGetLatestMsgResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLastMsgtime_:1;
  BOOL hasLastMsgid_:1;
  UInt64 lastMsgtime;
  UInt64 lastMsgid;
  NSMutableArray * msgsArray;
}
- (BOOL) hasLastMsgtime;
- (BOOL) hasLastMsgid;
@property (readonly, strong) NSArray * msgs;
@property (readonly) UInt64 lastMsgtime;
@property (readonly) UInt64 lastMsgid;
- (CMsgPBContent*)msgsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgGetLatestMsgRespBuilder*) builder;
+ (CMsgGetLatestMsgRespBuilder*) builder;
+ (CMsgGetLatestMsgRespBuilder*) builderWithPrototype:(CMsgGetLatestMsgResp*) prototype;
- (CMsgGetLatestMsgRespBuilder*) toBuilder;

+ (CMsgGetLatestMsgResp*) parseFromData:(NSData*) data;
+ (CMsgGetLatestMsgResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetLatestMsgResp*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgGetLatestMsgResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgGetLatestMsgResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgGetLatestMsgResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgGetLatestMsgRespBuilder : PBGeneratedMessageBuilder {
@private
  CMsgGetLatestMsgResp* resultCmsgGetLatestMsgResp;
}

- (CMsgGetLatestMsgResp*) defaultInstance;

- (CMsgGetLatestMsgRespBuilder*) clear;
- (CMsgGetLatestMsgRespBuilder*) clone;

- (CMsgGetLatestMsgResp*) build;
- (CMsgGetLatestMsgResp*) buildPartial;

- (CMsgGetLatestMsgRespBuilder*) mergeFrom:(CMsgGetLatestMsgResp*) other;
- (CMsgGetLatestMsgRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgGetLatestMsgRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)msgs;
- (CMsgPBContent*)msgsAtIndex:(NSUInteger)index;
- (CMsgGetLatestMsgRespBuilder *)addMsgs:(CMsgPBContent*)value;
- (CMsgGetLatestMsgRespBuilder *)setMsgsArray:(NSArray *)array;
- (CMsgGetLatestMsgRespBuilder *)clearMsgs;

- (BOOL) hasLastMsgtime;
- (UInt64) lastMsgtime;
- (CMsgGetLatestMsgRespBuilder*) setLastMsgtime:(UInt64) value;
- (CMsgGetLatestMsgRespBuilder*) clearLastMsgtime;

- (BOOL) hasLastMsgid;
- (UInt64) lastMsgid;
- (CMsgGetLatestMsgRespBuilder*) setLastMsgid:(UInt64) value;
- (CMsgGetLatestMsgRespBuilder*) clearLastMsgid;
@end

@interface CMsgPushNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFromUid_:1;
  BOOL hasToUid_:1;
  BOOL hasMsgId_:1;
  BOOL hasTime_:1;
  BOOL hasMsgData_:1;
  BOOL hasMsgType_:1;
  UInt64 fromUid;
  UInt64 toUid;
  UInt64 msgId;
  UInt64 time;
  NSData* msgData;
  UInt32 msgType;
}
- (BOOL) hasFromUid;
- (BOOL) hasToUid;
- (BOOL) hasMsgId;
- (BOOL) hasTime;
- (BOOL) hasMsgType;
- (BOOL) hasMsgData;
@property (readonly) UInt64 fromUid;
@property (readonly) UInt64 toUid;
@property (readonly) UInt64 msgId;
@property (readonly) UInt64 time;
@property (readonly) UInt32 msgType;
@property (readonly, strong) NSData* msgData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgPushNotifyBuilder*) builder;
+ (CMsgPushNotifyBuilder*) builder;
+ (CMsgPushNotifyBuilder*) builderWithPrototype:(CMsgPushNotify*) prototype;
- (CMsgPushNotifyBuilder*) toBuilder;

+ (CMsgPushNotify*) parseFromData:(NSData*) data;
+ (CMsgPushNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgPushNotify*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgPushNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgPushNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgPushNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgPushNotifyBuilder : PBGeneratedMessageBuilder {
@private
  CMsgPushNotify* resultCmsgPushNotify;
}

- (CMsgPushNotify*) defaultInstance;

- (CMsgPushNotifyBuilder*) clear;
- (CMsgPushNotifyBuilder*) clone;

- (CMsgPushNotify*) build;
- (CMsgPushNotify*) buildPartial;

- (CMsgPushNotifyBuilder*) mergeFrom:(CMsgPushNotify*) other;
- (CMsgPushNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgPushNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUid;
- (UInt64) fromUid;
- (CMsgPushNotifyBuilder*) setFromUid:(UInt64) value;
- (CMsgPushNotifyBuilder*) clearFromUid;

- (BOOL) hasToUid;
- (UInt64) toUid;
- (CMsgPushNotifyBuilder*) setToUid:(UInt64) value;
- (CMsgPushNotifyBuilder*) clearToUid;

- (BOOL) hasMsgId;
- (UInt64) msgId;
- (CMsgPushNotifyBuilder*) setMsgId:(UInt64) value;
- (CMsgPushNotifyBuilder*) clearMsgId;

- (BOOL) hasTime;
- (UInt64) time;
- (CMsgPushNotifyBuilder*) setTime:(UInt64) value;
- (CMsgPushNotifyBuilder*) clearTime;

- (BOOL) hasMsgType;
- (UInt32) msgType;
- (CMsgPushNotifyBuilder*) setMsgType:(UInt32) value;
- (CMsgPushNotifyBuilder*) clearMsgType;

- (BOOL) hasMsgData;
- (NSData*) msgData;
- (CMsgPushNotifyBuilder*) setMsgData:(NSData*) value;
- (CMsgPushNotifyBuilder*) clearMsgData;
@end

@interface CMsgMergeMsgReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMergeImtoken_:1;
  NSString* mergeImtoken;
}
- (BOOL) hasMergeImtoken;
@property (readonly, strong) NSString* mergeImtoken;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgMergeMsgReqBuilder*) builder;
+ (CMsgMergeMsgReqBuilder*) builder;
+ (CMsgMergeMsgReqBuilder*) builderWithPrototype:(CMsgMergeMsgReq*) prototype;
- (CMsgMergeMsgReqBuilder*) toBuilder;

+ (CMsgMergeMsgReq*) parseFromData:(NSData*) data;
+ (CMsgMergeMsgReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgMergeMsgReq*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgMergeMsgReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgMergeMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgMergeMsgReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgMergeMsgReqBuilder : PBGeneratedMessageBuilder {
@private
  CMsgMergeMsgReq* resultCmsgMergeMsgReq;
}

- (CMsgMergeMsgReq*) defaultInstance;

- (CMsgMergeMsgReqBuilder*) clear;
- (CMsgMergeMsgReqBuilder*) clone;

- (CMsgMergeMsgReq*) build;
- (CMsgMergeMsgReq*) buildPartial;

- (CMsgMergeMsgReqBuilder*) mergeFrom:(CMsgMergeMsgReq*) other;
- (CMsgMergeMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgMergeMsgReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMergeImtoken;
- (NSString*) mergeImtoken;
- (CMsgMergeMsgReqBuilder*) setMergeImtoken:(NSString*) value;
- (CMsgMergeMsgReqBuilder*) clearMergeImtoken;
@end

@interface CMsgMergeMsgResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgMergeMsgRespBuilder*) builder;
+ (CMsgMergeMsgRespBuilder*) builder;
+ (CMsgMergeMsgRespBuilder*) builderWithPrototype:(CMsgMergeMsgResp*) prototype;
- (CMsgMergeMsgRespBuilder*) toBuilder;

+ (CMsgMergeMsgResp*) parseFromData:(NSData*) data;
+ (CMsgMergeMsgResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgMergeMsgResp*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgMergeMsgResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgMergeMsgResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgMergeMsgResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgMergeMsgRespBuilder : PBGeneratedMessageBuilder {
@private
  CMsgMergeMsgResp* resultCmsgMergeMsgResp;
}

- (CMsgMergeMsgResp*) defaultInstance;

- (CMsgMergeMsgRespBuilder*) clear;
- (CMsgMergeMsgRespBuilder*) clone;

- (CMsgMergeMsgResp*) build;
- (CMsgMergeMsgResp*) buildPartial;

- (CMsgMergeMsgRespBuilder*) mergeFrom:(CMsgMergeMsgResp*) other;
- (CMsgMergeMsgRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgMergeMsgRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgClearUnreadByUidReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  UInt64 uid;
}
- (BOOL) hasUid;
@property (readonly) UInt64 uid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgClearUnreadByUidReqBuilder*) builder;
+ (CMsgClearUnreadByUidReqBuilder*) builder;
+ (CMsgClearUnreadByUidReqBuilder*) builderWithPrototype:(CMsgClearUnreadByUidReq*) prototype;
- (CMsgClearUnreadByUidReqBuilder*) toBuilder;

+ (CMsgClearUnreadByUidReq*) parseFromData:(NSData*) data;
+ (CMsgClearUnreadByUidReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgClearUnreadByUidReq*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgClearUnreadByUidReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgClearUnreadByUidReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgClearUnreadByUidReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgClearUnreadByUidReqBuilder : PBGeneratedMessageBuilder {
@private
  CMsgClearUnreadByUidReq* resultCmsgClearUnreadByUidReq;
}

- (CMsgClearUnreadByUidReq*) defaultInstance;

- (CMsgClearUnreadByUidReqBuilder*) clear;
- (CMsgClearUnreadByUidReqBuilder*) clone;

- (CMsgClearUnreadByUidReq*) build;
- (CMsgClearUnreadByUidReq*) buildPartial;

- (CMsgClearUnreadByUidReqBuilder*) mergeFrom:(CMsgClearUnreadByUidReq*) other;
- (CMsgClearUnreadByUidReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgClearUnreadByUidReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt64) uid;
- (CMsgClearUnreadByUidReqBuilder*) setUid:(UInt64) value;
- (CMsgClearUnreadByUidReqBuilder*) clearUid;
@end

@interface CMsgClearUnreadByUidResp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CMsgClearUnreadByUidRespBuilder*) builder;
+ (CMsgClearUnreadByUidRespBuilder*) builder;
+ (CMsgClearUnreadByUidRespBuilder*) builderWithPrototype:(CMsgClearUnreadByUidResp*) prototype;
- (CMsgClearUnreadByUidRespBuilder*) toBuilder;

+ (CMsgClearUnreadByUidResp*) parseFromData:(NSData*) data;
+ (CMsgClearUnreadByUidResp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgClearUnreadByUidResp*) parseFromInputStream:(NSInputStream*) input;
+ (CMsgClearUnreadByUidResp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CMsgClearUnreadByUidResp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CMsgClearUnreadByUidResp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CMsgClearUnreadByUidRespBuilder : PBGeneratedMessageBuilder {
@private
  CMsgClearUnreadByUidResp* resultCmsgClearUnreadByUidResp;
}

- (CMsgClearUnreadByUidResp*) defaultInstance;

- (CMsgClearUnreadByUidRespBuilder*) clear;
- (CMsgClearUnreadByUidRespBuilder*) clone;

- (CMsgClearUnreadByUidResp*) build;
- (CMsgClearUnreadByUidResp*) buildPartial;

- (CMsgClearUnreadByUidRespBuilder*) mergeFrom:(CMsgClearUnreadByUidResp*) other;
- (CMsgClearUnreadByUidRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CMsgClearUnreadByUidRespBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end


// @@protoc_insertion_point(global_scope)
